version: '3.9'
services:
  mongo:
    container_name: mongodb
    tty: true
    stdin_open: true
    restart: on-failure
    image: 'mongo'
    env_file:
      - ./mongo.env
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge